### ISSUE TITLE
As someone hosting an event, I want the system to stop me if I have forgotten key details on the form I filled out to create an event. (img URL, title length, location name length, numbers associated with: yr, month, hr, minute)

### ISSUE THREAD

**Issue by arr58** [twilight-magnitude/mgt656-spring-2015-project#34]

**Comment by MGT656student** [comment]
Does this mean immediately?  Or does displaying errors after submission suffice?

**Comment by arr58** [comment]
I think after submission is fine.

On Nov 20, 2015, at 10:04 AM, Mitch Rose <notifications@github.com<mailto:notifications@github.com>> wrote:

Does this mean immediately? Or does displaying errors after submission suffice?
