### ISSUE TITLE
As an event host, if the event I have created is not a valid form, I want to be notified and re-directed to the form with errors highlighted, so I can easily change them.

### ISSUE THREAD

**Issue by arr58** [twilight-magnitude/mgt656-spring-2015-project#37]

**Comment by marianaol** [comment]
I've been going over this and I can't really tell the difference with #53. I'll ask on Monday anyway.

**Comment by MGT656student** [comment]
I believe this is just the highlighting part.  I'm not sure what they mean by highlighting - do the boxes themselves have to be boxed out in red for example?  As it sits now, it displays the errors on the top of the page.  I'll send picture to the group on whatsapp.
