### ISSUE TITLE
Basic validations for event creation form

### ISSUE THREAD

**Issue by MGT656student** [twilight-magnitude/mgt656-spring-2015-project#53]

**Comment by MGT656student** [comment]
Check marks mean they are complete.  

   The form for creating new events
     ✓ should display errors to the user when the year is not an integer
     ✓ should display errors to the user when the year is more than 2016
     ✓ should display errors to the user when the year is less than 2015
     ✓ should display errors to the user when the month is not an integer
     ✓ should display errors to the user when the month is more than 11
     ✓ should display errors to the user when the month is less than 0
     ✓ should display errors to the user when the day is not an integer
     ✓ should display errors to the user when the day is more than 31
     ✓ should display errors to the user when the day is less than 1
     ✓ should display errors to the user when the hour is not an integer
     ✓ should display errors to the user when the hour is more than 23
     ✓ should display errors to the user when the hour is less than 0
     12) should display errors to the user when the image is not a gif or png
     13) should display errors to the user when the image is not a URL
     14) should display errors to the user when the location is too long
     15) should display errors to the user when the location is empty
     ✓ should display errors to the user when the title is too long
     ✓ should display errors to the user when the title is empty
     16) should redirect the user to the event detail page if the form is valid

**Comment by MGT656student** [comment]
Code for remaining tests written (except for 16); however, not passing tests.  Must see TA.

**Comment by marianaol** [comment]
Just finished working on 16 (test ok).

**Comment by MGT656student** [comment]
Validations all pass except for 16.  Must merge Marianas 16 test with Mitch's work.
